INSERT INTO CATEGORY VALUES(1, 'Books');
INSERT INTO CATEGORY VALUES(2, 'Eletronics');
INSERT INTO CATEGORY VALUES(3, 'Games');
INSERT INTO CATEGORY VALUES(4, 'Gadgets');
INSERT INTO CATEGORY VALUES(5, 'Food');